//@codekit-append "vendor/jquery.fitvids.min.js"
//@codekit-append "vendor/jquery.flexslider-min.js"
//@codekit-append "vendor/jquery.fancybox.pack.js"
//@codekit-append "vendor/jquery.scrollTo-1.4.3.1-min.js"
//@codekit-append "vendor/jquery.localscroll-1.2.7-min.js"